"use server";

import { auth } from "@/auth";
import prisma from "@/lib/prisma";
import { revalidatePath } from "next/cache";

export async function createCircle(formData: FormData) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const name = formData.get("name") as string;
  const description = formData.get("description") as string;
  // inviteCode is automatically generated by default in schema

  const circle = await prisma.circle.create({
    data: {
      name,
      description,
      ownerId: session.user.id,
      members: {
        create: {
          userId: session.user.id,
          role: "OWNER",
        },
      },
    },
  });

  revalidatePath("/");
  return circle;
}

export async function getMyCircles() {
  const session = await auth();
  if (!session?.user?.id) return [];

  return await prisma.circle.findMany({
    where: {
      members: {
        some: {
          userId: session.user.id,
        },
      },
    },
    include: {
      _count: {
        select: { members: true },
      },
      owner: true,
    },
  });
}

export async function getCircle(id: string) {
  const session = await auth();
  if (!session?.user?.id) return null;

  const circle = await prisma.circle.findUnique({
    where: { id },
    include: {
      members: {
        include: {
          user: true,
        },
      },
      invites: {
        orderBy: { eventDate: "desc" },
        include: {
          _count: {
            select: { rsvps: true },
          },
        },
      },
      owner: true,
    },
  });

  if (!circle) return null;

  // Authorization check: User must be a member
  const isMember = circle.members.some(
    (member) => member.userId === session.user.id,
  );

  if (!isMember) return null;

  return circle;
}

export async function regenerateInviteCode(circleId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { id: circleId },
  });

  if (!circle || circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized");
  }

  const { nanoid } = await import("nanoid");
  const newCode = nanoid(10);

  await prisma.circle.update({
    where: { id: circleId },
    data: { inviteCode: newCode },
  });

  revalidatePath(`/circle/${circleId}`);
  return newCode;
}

export async function joinCircleByCode(code: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { inviteCode: code },
    include: { members: true },
  });

  if (!circle) throw new Error("Invalid invite code");

  const isMember = circle.members.some(
    (member) => member.userId === session.user.id,
  );

  if (isMember) {
    return { success: true, circleId: circle.id, alreadyMember: true };
  }

  await prisma.circle.update({
    where: { id: circle.id },
    data: {
      members: {
        create: {
          userId: session.user.id,
          role: "MEMBER",
        },
      },
    },
  });

  revalidatePath(`/circle/${circle.id}`);
  revalidatePath("/");
  return { success: true, circleId: circle.id };
}

export async function getCircleByInviteCode(code: string) {
  const circle = await prisma.circle.findUnique({
    where: { inviteCode: code },
    include: {
      owner: true,
      _count: {
        select: { members: true },
      },
    },
  });
  return circle;
}

export async function deleteCircle(circleId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { id: circleId },
  });

  if (!circle) throw new Error("Circle not found");

  if (circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized: Only the owner can delete this circle");
  }

  await prisma.circle.delete({
    where: { id: circleId },
  });

  revalidatePath("/");
  return { success: true };
}
